### ISSUE TITLE
Expanding MCQuant nf-core module

### ISSUE THREAD

**Issue by LukasHats** [nf-core/mcmicro#46]
### Description of feature

Currently MCQuant has the option to pass additional skimage regionprops using the CLI, which is very nice. We would like to extend that by including specific glcm features in the MCQuant script. 
Further, we would like McQuant to accept all available bioformats (e.g. also qptiff)
Other adjustments might have to be implemented if SpatialData is included (again depending on where - from start, after ASHLAR or after quant?)
```[tasklist]
### Tasks
- [x] Add glcm features
- [x] change bioformats accepted by MCQuant
- [ ] optional: implementation with SpatialData
- [ ] change the version output in the nf-core mcquant module (currently hard coded) with the new version CLI output of MCQUANT
```

**Comment by LukasHats** [comment]
Added a [PR](https://github.com/labsyspharm/quantification/pull/49) in the mcquant repo
